name: action de prueba
on:
  push:
    branches:
      - main
jobs:
  dependences:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: node_modules_artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
      
  test:
    needs: dependences
    runs-on: ubuntu-20.04
    steps:
      - run: echo "running parallel 2"
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules_artifact
      - run: npm run build