name: action de prueba
on:
  push:
    branches:
      - main
jobs:
  dependences:
    runs-on: ubuntu-20.04
    steps:
      - run: npm install
  test:
    needs: dependences
    runs-on: ubuntu-20.04
    steps:
      - run: echo "running parallel 2"
  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - run: npm run build